import { Timestamp } from 'firebase/firestore'; // Import Timestamp for date fields

/**
 * Represents a user document in the 'users' Firestore collection.
 */
export interface User {
  id?: string; // Firestore document ID is often used as the 'id' field, but it's optional for new documents
  fullname: string;
  email: string;
  password: string;
  subscriptionId: string | null;
  avatarUrl: string | null;
  createdAt: Timestamp; // Using Firestore's Timestamp for dates
  updatedAt: Timestamp;
  defaultPaymentMethodId: string | null;
  stripeCustomerId: string | null;
}

/**
 * Represents the shape of data when creating a new user.
 * 'createdAt' might be set by the server, and 'id' is generated by Firestore.
 */
export type NewUser = Omit<User, 'id' | 'createdAt'> & {
  createdAt?: Timestamp; // Allow createdAt to be optional for creation, as it might be server-generated
};
