import type {
  CampaignReportNarrative,
  CampaignReportPacket,
} from "@/types/campaignReport";

function formatRevenue(cents: number, currency: string | null): string {
  if (cents === 0) return "0";
  const amount = (cents / 100).toFixed(2);
  return currency ? `${amount} ${currency}` : `${amount}`;
}

function metricsSection(packet: CampaignReportPacket): string {
  const { totals } = packet;
  const lines: string[] = [
    "## Metrics (verified data)",
    "",
    "| Metric | Value |",
    "|--------|-------|",
    `| Events | ${totals.event_count} |`,
    `| Total registrations | ${totals.attendee_count} |`,
    `| Paid registrations | ${totals.paid_count} |`,
    `| Free registrations | ${totals.free_count} |`,
    `| Revenue | ${formatRevenue(totals.revenue_cents, totals.currency)} |`,
    `| Creative assets | ${totals.asset_count} |`,
    `| Form responses | ${totals.form_response_count} |`,
    `| Announcements | ${totals.announcement_count} |`,
    `| Payments recorded | ${totals.payment_count} |`,
    "",
  ];

  if (totals.registrations_by_day.length > 0) {
    lines.push("### Registrations by day (all events)", "", "| Date | Count |", "|------|-------|");
    for (const row of totals.registrations_by_day) {
      lines.push(`| ${row.date} | ${row.count} |`);
    }
    lines.push("");
  }

  if (packet.events.length > 0) {
    lines.push("### Per-event metrics", "");
    for (const ev of packet.events) {
      const a = ev.analytics;
      lines.push(
        `#### ${ev.title}`,
        "",
        `- Registrations: ${a.attendee_count} (paid: ${a.paid_count})`,
        `- Revenue: ${formatRevenue(a.revenue_cents, a.currency)}`,
        `- Form responses: ${a.response_count}`,
        ev.price_summary ? `- Ticket: ${ev.price_summary}` : "",
        "",
      );
    }
  }

  if (packet.assets.items.length > 0) {
    lines.push("### Assets", "", "| Kind | Label | Status |", "|------|-------|--------|");
    for (const item of packet.assets.items) {
      lines.push(
        `| ${item.kind} | ${item.label ?? "—"} | ${item.status} |`,
      );
    }
    lines.push("");
  }

  return lines.join("\n");
}

export function renderReportMarkdown(
  packet: CampaignReportPacket,
  narrative: CampaignReportNarrative,
): string {
  const generated = new Date(packet.generated_at).toLocaleString("en-US", {
    dateStyle: "long",
    timeStyle: "short",
  });

  const insights = narrative.insights.map((i) => `- ${i}`).join("\n");
  const recommendations = narrative.recommendations
    .map((r) => `- ${r}`)
    .join("\n");

  return [
    `# Campaign Report: ${packet.campaign.title}`,
    "",
    `**Generated:** ${generated}  `,
    `**Status:** ${packet.campaign.status}  `,
    `**Goal:** ${packet.campaign.goal_prompt}`,
    "",
    "---",
    "",
    "## Executive summary",
    "",
    narrative.executive_summary,
    "",
    "## Campaign overview",
    "",
    narrative.campaign_overview,
    "",
    "## Strategy highlights",
    "",
    narrative.strategy_highlights,
    "",
    "## Content and assets",
    "",
    narrative.content_and_assets,
    "",
    metricsSection(packet),
    "## Performance analysis",
    "",
    narrative.performance_analysis,
    "",
    "## Insights",
    "",
    insights,
    "",
    "## Recommendations",
    "",
    recommendations,
    "",
    "## Data limitations",
    "",
    narrative.limitations_note,
    "",
    "---",
    "",
    "_Report generated by SoloScale. Metrics tables reflect live Firestore data at generation time._",
  ].join("\n");
}
